version: '3.1'
services:
  mariadb:
    image: debian:buster
    container_name: mariadb
    restart: always
    volumes:
      - ~/data/maria/:/var/lib/mysql
    environment:
      DB_LOGIN: "${DB_LOGIN}"
      DB_PASS: "${DB_PASS}"
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - some-net
    env_file:
      - .env
  nginx:
    image: debian:buster
    container_name: webserver
    restart: always
    extra_hosts:
      - "lmorgana.42.fr:127.0.0.1"
    volumes:
      - ~/data/wp:/var/www/wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - some-net
    env_file:
      - .env
  wordpress:
    image: debian:buster
    container_name: wordpress
    restart: always
    volumes:
      - ~/data/wp:/var/www/wordpress
    environment:
      WP_USER1_LOGIN: "${WP_USER1_LOGIN}"
      WP_USER1_PASS: "${WP_USER1_PASS}"
      WP_USER2_LOGIN: "${WP_USER2_LOGIN}"
      WP_USER2_PASS: "${WP_USER2_PASS}"
      DB_LOGIN: "${DB_LOGIN}"
      DB_PASS: "${DB_PASS}"
    ports:
      - "9000:9000"
    build:
      context: ./requirements/WordPress
      dockerfile: Dockerfile
    networks:
      - some-net
    env_file:
      - .env
networks:
  some-net:
    driver: bridge